### ISSUE TITLE
Problem with Wordcloud

### ISSUE THREAD

**Issue by tassieg** [cyberdh/Text-Analysis#64]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b1de30562c59> in <module>()
----> 1 from nltk.corpus import stopwords
      2 import string
      3 from collections import defaultdict
      4 import wordcloud
      5 import matplotlib.pyplot as plt

/N/soft/rhel7/anaconda/python3.6/4.3.1/lib/python3.6/site-packages/nltk/__init__.py in <module>()
    158     from nltk import cluster
    159 
--> 160 from nltk.downloader import download, download_shell
    161 try:
    162     import tkinter

/N/soft/rhel7/anaconda/python3.6/4.3.1/lib/python3.6/site-packages/nltk/downloader.py in <module>()
   2231 
   2232 # Aliases
-> 2233 _downloader = Downloader()
   2234 download = _downloader.download
   2235 

/N/soft/rhel7/anaconda/python3.6/4.3.1/lib/python3.6/site-packages/nltk/downloader.py in __init__(self, server_index_url, download_dir)
    435         # decide where we're going to save things to.
    436         if self._download_dir is None:
--> 437             self._download_dir = self.default_download_dir()
    438 
    439     #/////////////////////////////////////////////////////////////////

/N/soft/rhel7/anaconda/python3.6/4.3.1/lib/python3.6/site-packages/nltk/downloader.py in default_download_dir(self)
    933         for nltkdir in nltk.data.path:
    934             if (os.path.exists(nltkdir) and
--> 935                 nltk.internals.is_writable(nltkdir)):
    936                 return nltkdir
    937 

AttributeError: module 'nltk' has no attribute 'internals'

**Comment by dkloster** [comment]
Added NLTK package to Python environment in cyberdh > Carbonate > dhPyEnviron > lib > python3.6 > site-packages. This seems to have solved the problem. Closing this issue.
