### ISSUE TITLE
Wordcloud Error in Last Cell

### ISSUE THREAD

**Issue by tassieg** [cyberdh/Text-Analysis#65]
I installed NLTK into the cyberdh environment, but final cell still throws an error:

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-11-3af3d9a233b1> in <module>()
     28 
     29     # Plot wordcloud from corpus
---> 30     drawWordCloudCorpus(corpusRoot, wcImgFilepath, dpi, maxWordCnt)

<ipython-input-10-be6fd89c9439> in drawWordCloudCorpus(corpusRoot, wcImgFilepath, dpi, maxWordCnt)
     15 
     16             with open(textFilepath, "r") as f:
---> 17                 text = f.read()
     18                 tokens.extend(textClean(text))
     19 

/N/soft/rhel7/anaconda/python3.6/4.3.1/lib/python3.6/encodings/ascii.py in decode(self, input, final)
     24 class IncrementalDecoder(codecs.IncrementalDecoder):
     25     def decode(self, input, final=False):
---> 26         return codecs.ascii_decode(input, self.errors)[0]
     27 
     28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 301: ordinal not in range(128)

**Comment by dkloster** [comment]
The problem was that the code did not encode in utf-8 when running the notebook on an entire directory. It was only doing it when running it on a single file. I corrected this in all the word cloud notebooks and scripts.
